# This version of .travis.yml always downloads the stable version of
# phantom-qunit.js before running the tests, so you don't have to check
# phantom-xxx.js into your repository.  Make sure to change qunit to jasmine or
# mocha if necessary.  If you aren't sure which version of .travis.yml to use,
# pick this one.

# We aren't actually using any particular language here, so let's use Ruby
# since that's probably the most likely Travis worker to be available
language: ruby
rvm:
  - 1.9.3
notifications:
  email: false
before_script:
  # Travis needs this stuff to start Phantom1.4...
  # When they get Phantom1.5 this section can go away
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  # Change these to jasmine or mocha if necessary
  - "wget https://raw.github.com/mark-rushakoff/OpenPhantomScripts/master/phantom-jasmine.js"
  # Make sure to change test/test.html to the path to your test page
  - "phantomjs phantom-jasmine.js tests/index.html"
  - "phantomjs phantom-jasmine.js tests/index-amd.html"
